// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMjEnVXoNRmgJj6afTZuMZqNbg4bN9Dgo',
    appId: '1:285269990193:web:4d403b35d548444abaae10',
    messagingSenderId: '285269990193',
    projectId: 'forms-66186',
    authDomain: 'forms-66186.firebaseapp.com',
    storageBucket: 'forms-66186.firebasestorage.app',
    measurementId: 'G-6YPFKXFQ8J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtybXfry1pUX1SBG0uiocuWDVpBKCEUnk',
    appId: '1:285269990193:ios:172b44eee61b987bbaae10',
    messagingSenderId: '285269990193',
    projectId: 'forms-66186',
    storageBucket: 'forms-66186.firebasestorage.app',
    iosBundleId: 'com.example.formsApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtybXfry1pUX1SBG0uiocuWDVpBKCEUnk',
    appId: '1:285269990193:ios:172b44eee61b987bbaae10',
    messagingSenderId: '285269990193',
    projectId: 'forms-66186',
    storageBucket: 'forms-66186.firebasestorage.app',
    iosBundleId: 'com.example.formsApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIrpkSISW8GvxqnY9zc2mcVHSNSA9jmAs',
    appId: '1:285269990193:android:dcddf99ad6d7e000baae10',
    messagingSenderId: '285269990193',
    projectId: 'forms-66186',
    storageBucket: 'forms-66186.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMjEnVXoNRmgJj6afTZuMZqNbg4bN9Dgo',
    appId: '1:285269990193:web:cbdde00f535c7906baae10',
    messagingSenderId: '285269990193',
    projectId: 'forms-66186',
    authDomain: 'forms-66186.firebaseapp.com',
    storageBucket: 'forms-66186.firebasestorage.app',
    measurementId: 'G-ZPSCM38MRD',
  );

}