// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kvR8kMd58VaxG_Jav51djBKD-H2ybGQ',
    appId: '1:826968691664:web:2dc0cc767fa54f2b4a5fd5',
    messagingSenderId: '826968691664',
    projectId: 'forms-d51f6',
    authDomain: 'forms-d51f6.firebaseapp.com',
    storageBucket: 'forms-d51f6.appspot.com',
    measurementId: 'G-58MTH6VZSZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH1yIDSmn9rakoSIr78-GpJ1IqZhc5Qpg',
    appId: '1:826968691664:ios:54224122c676df4a4a5fd5',
    messagingSenderId: '826968691664',
    projectId: 'forms-d51f6',
    storageBucket: 'forms-d51f6.appspot.com',
    iosBundleId: 'com.example.formsApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1yIDSmn9rakoSIr78-GpJ1IqZhc5Qpg',
    appId: '1:826968691664:ios:54224122c676df4a4a5fd5',
    messagingSenderId: '826968691664',
    projectId: 'forms-d51f6',
    storageBucket: 'forms-d51f6.appspot.com',
    iosBundleId: 'com.example.formsApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK555M2duBZKjhMnVja4MQ3Qsa2M6If68',
    appId: '1:826968691664:android:3e9bb5fb3c84a8fa4a5fd5',
    messagingSenderId: '826968691664',
    projectId: 'forms-d51f6',
    storageBucket: 'forms-d51f6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6kvR8kMd58VaxG_Jav51djBKD-H2ybGQ',
    appId: '1:826968691664:web:835ba8d455bd9f824a5fd5',
    messagingSenderId: '826968691664',
    projectId: 'forms-d51f6',
    authDomain: 'forms-d51f6.firebaseapp.com',
    storageBucket: 'forms-d51f6.appspot.com',
    measurementId: 'G-1EZCL2GWW2',
  );

}